# Generated by Django 4.0.2 on 2022-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
