# Generated by Django 4.0.2 on 2022-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_homework_id_alter_homework_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
