# Generated by Django 4.0.2 on 2022-03-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_homework_id_alter_homework_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='phone',
        ),
    ]
