# Generated by Django 4.0.2 on 2022-03-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_remove_homework_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='email',
        ),
    ]
