# Generated by Django 4.0.2 on 2022-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_alter_homework_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_active',
            field=models.BooleanField(choices=[(0, 'Yes'), (1, 'No'), (2, 'YES/NO')], default=0),
        ),
    ]
