# Generated by Django 4.0.2 on 2022-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_homework_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
    ]
